"""
Business Logic & Domain Services Layer for CATALYST.
Access subpackages directly:
  from backend.services.agents import ...
  from backend.services.document import ...
  from backend.services.retrieval import ...
  from backend.services.llm import ...
  from backend.services.memory import ...
  from backend.services.nlp import ...
  from backend.services.curriculum import ...
  from backend.services.analytics import ...
  from backend.services.workspace import ...
  from backend.services.system import ...
"""
